require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'lib/webkit_stderr_with_qt_plugin_messages_suppressed.rb'
    - '/**/tovgdb.rake'

Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

Documentation:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true
  Exclude:
    - '/**/game.rb'

Layout/SpaceInsideBrackets:
  Enabled: true
  Exclude:
    - '/**/game.rb'

Metrics/AbcSize:
  Enabled: true
  Max: 16
  Exclude:
    - '/**/admin_game_tag.rb'
    - '/**/active_admin.rb'
    - '/**/20160211150539_create_indexs.rb'
    - '/**/20160317155449_no_nil_allowed_for_string_and_text_fields.rb'
    - '/**/tovgdb_spec_helper.rb'

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Enabled: true
  Exclude:
  - '/**/application_helper.rb'

Metrics/BlockLength:
  Enabled: false
  # Exclude:
  #   - 'Gemfile'

Metrics/BlockNesting:
  Enabled: true
  Exclude:
    - '/**/tovgdb.rake'

Metrics/LineLength:
  Max: 170
  Enabled: true
  Exclude:
    - '/**/application_helper.rb'
    - '/**/description.rb'
    - '/**/game_model_helpers_spec.rb'
    - '/**/20151207173441_devise_create_admin_users.rb'
    - '/**/tovgdb.rake'

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - '/**/games_controller.rb'
    - '/**/game_search.rb'
    - '/**/admin_game_tag.rb'
    - '/**/active_admin.rb'
    - '/**/application_helper.rb'
    - '/**/game_search.rb'
    - '/**/active_admin.rb'
    - '/**/20151207173441_devise_create_admin_users.rb'
    - '/**/20151207173444_create_active_admin_comments.rb'
    - '/**/20160129173455_create_themes.rb'
    - '/**/20160211150539_create_indexs.rb'
    - '/**/20160317155449_no_nil_allowed_for_string_and_text_fields.rb'
    - '/**/20160709210349_drop_sub_genres.rb'
    - '/**/20170916144037_remove_awards.rb'

Metrics/PerceivedComplexity:
  Enabled: true
  Exclude:
    - '/**/application_helper.rb'

Rails/FindEach:
  Enabled: true
  Exclude:
    - '/**/app/models/mode.rb'

Rails/DynamicFindBy:
  Enabled: false

# TODO: enable this and address issues
Rails/OutputSafety:
  Enabled: false

Rails/Output:
  Enabled: true
  Exclude:
    - '/**/lib/tasks/move_subgenre_to_genre.rb'

RSpec/DescribeClass:
  Enabled: true
  Exclude:
    - '/**/admin/session_spec.rb'
    - '/**/admin/tags_spec.rb'
    - '/**/admin/tags_spec.rb'
    - '/**/game_associations_spec.rb'

RSpec/ExampleLength:
  Enabled: false

# RSpec/FilePath:
#   Enabled: true
#   Exclude:
#     - '/**/creators_spec.rb'

Style/ClassAndModuleChildren:
  Enabled: true
  Exclude:
    - '/**/Guardfile.rb'
    - '/**/Guardfile'


Style/FileName:
  Enabled: true
  Exclude:
    - '/**/Guardfile.rb'
    - 'Capfile'
    - 'Gemfile'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinGrouping:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: true
  Exclude:
    - '/**/tovgdb_search.rb'
