exclude: ['public/**', 'vendor/**']

linters:
  NestingDepth:
    max_depth: 5

  SelectorDepth:
    max_depth: 5

  ColorVariable:
    enabled: true
    exclude:
      - 'app/assets/stylesheets/scss/_colors.scss'
