exclude: ['public/**', 'vendor/**']

linters:

  ColorVariable:
    enabled: true
    exclude:
      - 'app/assets/stylesheets/scss/_colors.scss'

  IdSelector:
    enabled: false

  NestingDepth:
    max_depth: 5

  SelectorDepth:
    max_depth: 5

  SelectorFormat:
    enabled: true
    exclude:
      - 'app/assets/stylesheets/scss/_new_game.scss'
      - 'app/assets/stylesheets/scss/_form.scss'
