default: &default
  adapter: mysql2
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  encoding: utf8

development:
  <<: *default

test:
  <<: *default
  database: tovgdb_test
  username: travis

production:
  <<: *default
