default: &default
  adapter: mysql2
  database: <%= "#{Rails.application.class.parent_name.downcase}_#{Rails.env}" %>
  username: <%= ENV['TOVGDB_DATABASE_USER'] %>
  password: <%= ENV['TOVGDB_DATABASE_PASSWORD'] %>
  encoding: utf8

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
